// Copyright 2025 The go-ethereum Authors
// This file is part of the go-ethereum library.
//
// The go-ethereum library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-ethereum library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.

package filtermaps

import (
	"sync"
)

type IndexView struct {
	f       *FilterMaps
	chainView *ChainView
	maps    common.Range[uint32]
	blocks  common.Range[uint64] // fully rendered searchable blocks
	lock 	sync.RWMutex
	dbMapsBefore uint32
	dbBlocksBefore uint64
	overlay []*renderedMap
}

func (f *FilterMaps) NewIndexView(databaseMaps common.Range[uint32], chainView *ChainView) (*IndexView, error) {
	iv := &IndexView{
		f: f,
		chainView: chainView,
		maps: databaseMaps,
	}
	sharedMaps, err := iv.sharedMapRange(chainView)
	if err != nil {
		return nil, err
	}
	iv.maps = sharedMaps
	if err := iv.setBlockRange(); err != nil {
		return nil, err
	}
	iv.dbMapsBefore = iv.maps.AfterLast()
	iv.dbBlocksBefore = iv.blocks.AfterLast()
	return iv
}

// GetParams returns the filtermaps parameters.
func (iv *IndexView) GetParams() *Params {
	return &iv.f.Params
}

func (iv *IndexView) setBlockRange() error {
	var first, afterLast uint64
	if iv.maps.First() > 0 {
		lastBlock, _, _, err := iv.getLastBlockOfMap(sharedMaps.First()-1)
		if err != nil {
			return err
		}
		first = lastBlock+1
	}
	if iv.maps.AfterLast() > 0 {
		lastBlock, _, finished, err := iv.getLastBlockOfMap(sharedMaps.AfterLast()-1)
		if err != nil {
			return err
		}
		afterLast = lastBlock
		if finished {
			afterLast++
		}
	}
	if afterLast > first {
		iv.blocks = common.NewRange[uint64](first, afterLast-first)
	} else {
		iv.blocks = common.Range[uint64]{}
	}
	return nil
}

// zero length range means there are no shared maps but there is still a suitable initialization point
func (iv *IndexView) sharedMapRange(chainView *ChainView) (common.Range[uint32], error) {
	sharedMaps := iv.maps
	for sharedMaps.AfterLast() > 0 {
		lastBlock, lastBlockId, err := iv.getLastBlockOfMap(sharedMaps.AfterLast()-1) // not sharedMaps.Last() because it should work when sharedMaps.Count() == 0
		if err != nil {
			return common.Range[uint32]{}, err
		}
		if chainView.BlockId(lastBlock) == lastBlockId {
			return sharedMaps, nil
		}
		if sharedMaps.IsEmpty() {
			break
		}
		sharedMaps.SetAfterLast(sharedMaps.Last())
	}
	return common.Range[uint32]{}, nil
}

func (iv *IndexView) SharedBlockRange(chainView *ChainView) common.Range[uint64] {
	return iv.chainView.SharedRange(chainView).Intersection(iv.blocks)
}

// GetFilterMapRows fetches a set of filter map rows at the corresponding map
// indices and a shared row index. If baseLayerOnly is true then only the first
// baseRowLength entries are returned.
func (iv *IndexView) GetFilterMapRows(mapIndices []uint32, rowIndex uint32, baseLayerOnly bool) ([]FilterRow, error) {
	iv.lock.RLock()
	defer iv.lock.RUnlock()
	
	dbMaps := len(mapIndices)
	for dbMaps > 0 && mapIndices[dbMaps-1] >= iv.dbMapsBefore {
		dbMaps--
	}
	res, err := iv.f.getFilterMapRows(mapIndices[:dbMaps], rowIndex, baseLayerOnly)
	if err != nil {
		return nil, err
	}
	for i:=dbMaps;i<len(mapIndices);i++ {
		var row FilterRow
		if j := mapIndices[i]-iv.dbMapsBefore; j < uint32(len(iv.overlay)) {
			row = iv.overlay[j].fm[rowIndex]
		}
		res = append(res, row)
	}
	return res, nil
}

// GetBlockLvPointer returns the starting log value index where the log values
// generated by the given block are located.
func (iv *IndexView) GetBlockLvPointer(blockNumber uint64) (uint64, error) {
	iv.lock.RLock()
	defer iv.lock.RUnlock()

	if blockNumber < iv.dbBlocksBefore {	
		return iv.f.getBlockLvPointer(blockNumber)
	}
	for _, mm := range iv.overlay {
		if blockNumber <= mm.lastBlock {
			return mm.blockLvPtrs[blockNumber-mm.firstBlock()], nil
		}
	}
	return 0, errUnindexedRange
}

// getLastBlockOfMap returns the number and id of the block that generated the
// last log value entry of the given map. It also returns a boolean flag that
// signals if the last block is fully rendered.
func (iv *IndexView) getLastBlockOfMap(mapIndex uint32) (uint64, common.Hash, bool, error) {
	iv.lock.RLock()
	defer iv.lock.RUnlock()

	if mapIndex < iv.dbMapsBefore {	
		lastBlock, lastBlockId, err := iv.f.getLastBlockOfMap(mapIndex)
		return lastBlock, lastBlockId, false, err
	}
	if i := mapIndex-iv.dbMapsBefore; i<uint32(len(iv.overlay)) {
		mm := iv.overlay[i]
		return mm.lastBlock, mm.lastBlockId, mm.finished, nil 
	}
	return 0, nil, errUnindexedRange
}

// GetLogByLvIndex returns the log at the given log value index. If the index does
// not point to the first log value entry of a log then no log and no error are
// returned as this can happen when the log value index was a false positive.
func (iv *IndexView) GetLogByLvIndex(lvIndex uint64) (*types.Log, error) {
	mapIndex := uint32(lvIndex >> f.logValuesPerMap)
	if !iv.maps.Includes(mapIndex) {
		return nil, nil
	}
	// find possible block range based on map to block pointers
	lastBlockNumber, _, err := iv.getLastBlockOfMap(mapIndex)
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve last block of map %d containing searched log value index %d: %v", mapIndex, lvIndex, err)
	}
	var firstBlockNumber uint64
	if mapIndex > 0 {
		firstBlockNumber, _, err = iv.getLastBlockOfMap(mapIndex - 1)
		if err != nil {
			return nil, fmt.Errorf("failed to retrieve last block of map %d before searched log value index %d: %v", mapIndex, lvIndex, err)
		}
	}
	if firstBlockNumber < iv.blocks.First() {
		firstBlockNumber = iv.blocks.First()
	}
	// find block with binary search based on block to log value index pointers
	for firstBlockNumber < lastBlockNumber {
		midBlockNumber := (firstBlockNumber + lastBlockNumber + 1) / 2
		midLvPointer, err := iv.GetBlockLvPointer(midBlockNumber)
		if err != nil {
			return nil, fmt.Errorf("failed to retrieve log value pointer of block %d while binary searching log value index %d: %v", midBlockNumber, lvIndex, err)
		}
		if lvIndex < midLvPointer {
			lastBlockNumber = midBlockNumber - 1
		} else {
			firstBlockNumber = midBlockNumber
		}
	}
	// get block receipts
	receipts := iv.chainView.Receipts(firstBlockNumber)
	if receipts == nil {
		return nil, fmt.Errorf("failed to retrieve receipts for block %d containing searched log value index %d: %v", firstBlockNumber, lvIndex, err)
	}
	lvPointer, err := iv.GetBlockLvPointer(firstBlockNumber)
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve log value pointer of block %d containing searched log value index %d: %v", firstBlockNumber, lvIndex, err)
	}
	// iterate through receipts to find the exact log starting at lvIndex
	for _, receipt := range receipts {
		for _, log := range receipt.Logs {
			l := uint64(len(log.Topics) + 1)
			r := iv.f.valuesPerMap - lvPointer%iv.f.valuesPerMap
			if l > r {
				lvPointer += r // skip to map boundary
			}
			if lvPointer > lvIndex {
				// lvIndex does not point to the first log value (address value)
				// generated by a log as true matches should always do, so it
				// is considered a false positive (no log and no error returned).
				return nil, nil
			}
			if lvPointer == lvIndex {
				return log, nil // potential match
			}
			lvPointer += l
		}
	}
	return nil, nil
}
