// Copyright 2025 The go-ethereum Authors
// This file is part of the go-ethereum library.
//
// The go-ethereum library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-ethereum library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.

package filtermaps

import (
	"encoding/binary"
	"errors"
	"fmt"
	"math"
	"sync/atomic"
	"time"

	"github.com/ethereum/go-ethereum/beacon/merkle"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/mclock"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/log"
	"github.com/ethereum/go-ethereum/rlp"
)

var (
	ErrInvalidView = errors.New("index view already invalidated")
)

type IndexView struct {
	// if invalid <= 0 then the view is considered invalid and will return error
	// on any read operation (storage maps before firstMemoryMap might have changed
	// since its creation)
	refCount, invalid int32
	storage           *mapStorage

	tailEpoch     uint32               //TODO apply to read functions
	blockRange    common.Range[uint64] //TODO apply to read functions
	headBlockHash common.Hash
	nextEntry     uint64 // points after head block delimiter

	firstOverlayMap    uint32
	firstOverlayBlock  uint64
	overlayMaps        []*completedMap
	indexEntriesReader nodeReader
}

func (iv *IndexView) Release() {
	iv.addRefCount(-1)
}

func (iv *IndexView) addRefCount(add int32) bool {
	return atomic.AddInt32(&iv.refCount, add) <= 0
}

func (iv *IndexView) checkReleased() bool {
	return atomic.LoadInt32(&iv.refCount) <= 0
}

func (iv *IndexView) invalidate() {
	atomic.StoreInt32(&iv.invalid, 1)
}

func (iv *IndexView) checkInvalid() bool {
	return atomic.LoadInt32(&iv.invalid) != 0
}

func (iv *IndexView) GetParams() *Params {
	return iv.storage.params
}

func (iv *IndexView) BlockRange() common.Range[uint64] {
	return iv.blockRange
}

// getBlockLvPointer returns the starting log value index where the log values
// generated by the given block are located.
// Note that the function returns a valid result (the next free log value index)
// for headNumber + 1.
func (iv *IndexView) GetBlockLvPointer(blockNumber uint64) (uint64, error) {
	if iv.checkInvalid() {
		return 0, ErrInvalidView
	}

	if blockNumber < iv.firstOverlayBlock {
		lvPtr, err := iv.storage.getBlockLvPointer(blockNumber)
		if iv.checkInvalid() {
			return 0, ErrInvalidView
		}
		return lvPtr, err
	}
	if blockNumber == iv.blockRange.AfterLast() {
		return iv.nextEntry, nil
	}
	if blockNumber > iv.blockRange.AfterLast() {
		return 0, ErrOutOfRange
	}
	for _, fm := range iv.overlayMaps {
		if blockNumber >= fm.firstBlock() && blockNumber <= fm.lastBlock.number {
			return fm.blockPtrs[blockNumber-fm.firstBlock()], nil
		}
	}
	panic("IndexView.GetBlockLvPointer: gap in blockLvPtrs")
}

// GetLastBlockOfMap returns the number and hash of the block that generated the
// last log value entry of the given map.
func (iv *IndexView) GetLastBlockOfMap(mapIndex uint32) (uint64, common.Hash, error) {
	if iv.checkInvalid() {
		return 0, common.Hash{}, ErrInvalidView
	}

	if mapIndex < iv.firstOverlayMap {
		lastNumber, lastHash, err := iv.storage.getLastBlockOfMap(mapIndex)
		if iv.checkInvalid() {
			return 0, common.Hash{}, ErrInvalidView
		}
		return lastNumber, lastHash, err
	}
	i := mapIndex - iv.firstOverlayMap
	if i >= uint32(len(iv.overlayMaps)) {
		return 0, common.Hash{}, ErrOutOfRange
	}
	fm := iv.overlayMaps[i]
	return fm.lastBlock.number, fm.lastBlock.hash, nil
}

// GetFilterMapRows returns a batch of filter maps rows from the same row index,
// each truncated to the length limit of the specified mapping layer.
// The function assumes that the map indices are in strictly ascending order.
func (iv *IndexView) GetFilterMapRows(mapIndices []uint32, rowIndex, layerIndex uint32) (rows []FilterRow, err error) {
	if iv.checkInvalid() {
		return nil, ErrInvalidView
	}

	dbIndices := len(mapIndices)
	for dbIndices > 0 && mapIndices[dbIndices-1] >= iv.firstOverlayMap {
		dbIndices--
	}
	if dbIndices > 0 {
		rows, err = iv.storage.getFilterMapRows(mapIndices[:dbIndices], rowIndex, layerIndex)
		if iv.checkInvalid() {
			return nil, ErrInvalidView
		}
		if err != nil {
			return nil, err
		}
	}
	for i := dbIndices; i < len(mapIndices); i++ {
		mapIndex := mapIndices[i]
		var row FilterRow
		if i := mapIndex - iv.firstOverlayMap; i < uint32(len(iv.overlayMaps)) {
			row = iv.overlayMaps[i].getRow(rowIndex, iv.storage.params.getMaxRowLength(layerIndex+1))
		}
		rows = append(rows, row)
	}
	return rows, nil
}

func (iv *IndexView) getFilterMapRow(mapIndex, rowIndex uint32) (FilterRow, error) {
	if mapIndex < iv.firstOverlayMap {
		return iv.storage.getFilterMapRow(mapIndex, rowIndex)
	}
	i := mapIndex - iv.firstOverlayMap
	if i < uint32(len(iv.overlayMaps)) {
		return iv.overlayMaps[i].getRow(rowIndex, math.MaxUint32), nil
	}
	return nil, nil
}

func (iv *IndexView) getSubtree(gti treeIndex) (serializedSubtree, error) {
	mapIndex := uint32(iv.storage.params.subtreeLvRange(gti).Last() / iv.storage.params.valuesPerMap)
	if mapIndex < iv.firstOverlayMap {
		return iv.storage.getSubtree(gti)
	}
	i := mapIndex - iv.firstOverlayMap
	if i < uint32(len(iv.overlayMaps)) {
		return iv.overlayMaps[i].getSubtree(gti), nil
	}
	return nil, nil
}

func (iv *IndexView) initTree() (*merkleTree, error) {
	boundary := iv.storage.params.newLogIndexBoundaryReader(iv.nextEntry)
	nodeReader := mergedNodeReader{
		iv.storage.params.newFilterRowNodeReader(iv.getFilterMapRow).getNode,
		newSubtreeNodeReader(iv.getSubtree).getNode,
		boundary.getNode,
	}.getNode
	return iv.storage.params.newMerkleTree(nodeReader, boundary.nodeStatus)
}

type renderState struct {
	params           *Params
	renderRange      common.Range[uint32]
	nextEntry        uint64
	mapIndex         uint32
	currentMap       *memoryMap
	finishedMaps     []*completedMap
	nextBlock        uint64
	partialBlock     bool
	partialBlockHash common.Hash

	// initialized when currentMap != nil
	tree          *merkleTree
	mapRowRoots   []mtNode
	nextEntryNode mtNode
}

func (rs *renderState) checkNextHash(hash common.Hash) bool {
	if rs.partialBlock && rs.partialBlockHash != hash {
		return false
	}
	rs.partialBlock = false
	return true
}

func uint64ToValue(v uint64) (result merkle.Value) {
	binary.LittleEndian.PutUint64(result[:8], v)
	return
}

func (rs *renderState) addTxAndLogEntries(transactions []*types.Transaction, receipts types.Receipts) {
	TTaddTxAndLogEntries -= mclock.Now()
	defer func() { TTaddTxAndLogEntries += mclock.Now() }()

	if rs.partialBlock {
		panic("checkNextHash has to be called before adding partially rendered block")
	}
	if rs.currentMap != nil {
		rs.currentMap.blockPtrs = append(rs.currentMap.blockPtrs, rs.nextEntry)
		rs.currentMap.lastBlock = lastBlockOfMap{number: rs.nextBlock} // hash will be set by addBlockEntry
	}
	for i, receipt := range receipts {
		txHash := transactions[i].Hash()
		if rs.currentMap != nil {
			receiptRlp, err := rlp.EncodeToBytes(receipt)
			if err != nil {
				log.Error("Failed to encode receipt", "error", err)
			}
			rs.addTxMeta(rs.nextBlock, txHash, i, crypto.Keccak256Hash(receiptRlp))
			rs.addValue(txValue(txHash))
		} else {
			rs.advance(1)
		}
		for j, log := range receipt.Logs {
			mapRemaining := rs.params.valuesPerMap - rs.nextEntry%rs.params.valuesPerMap
			if mapRemaining <= uint64(len(log.Topics)) {
				rs.advance(mapRemaining)
			}
			if rs.currentMap != nil {
				rs.addLogEntryAndMeta(log, rs.nextBlock, txHash, i, j)
				rs.addValue(addressValue(log.Address))
				for _, topic := range log.Topics {
					rs.addValue(topicValue(topic))
				}
			} else {
				rs.advance(uint64(len(log.Topics) + 1))
			}
			if rs.finished() {
				return
			}
		}
	}
	if rs.tree != nil {
		// update next_index pointer
		nextEntryNode := rs.tree.getDescendant(rs.params.treeRoot, ti64(rtiNextEntry))
		rs.tree.setValue(nextEntryNode.index, uint64ToValue(rs.nextEntry), 1)
	}
}

func (rs *renderState) addBlockEntry(header *types.Header) (uint32, []*completedMap) {
	TTaddBlockEntry -= mclock.Now()
	defer func() { TTaddBlockEntry += mclock.Now() }()

	if rs.partialBlock {
		panic("checkNextHash has to be called before adding partially rendered block")
	}
	number, hash := header.Number.Uint64(), header.Hash()
	if rs.nextBlock != number {
		panic("wrong block number")
	}
	if rs.currentMap != nil {
		rs.addBlockMeta(number, hash, header.Time)
		rs.addValue(blockValue(hash))
	}
	rs.nextBlock++
	lastBlock := lastBlockOfMap{number: number, hash: hash}
	if rs.currentMap != nil {
		rs.currentMap.lastBlock = lastBlock
	}
	for _, fm := range rs.finishedMaps {
		fm.lastBlock = lastBlock
	}
	firstMemoryMap, finishedMaps := rs.mapIndex-uint32(len(rs.finishedMaps)), rs.finishedMaps
	rs.finishedMaps = nil
	return firstMemoryMap, finishedMaps
}

// assumes currentMap != nil
func (rs *renderState) addValue(mapValue common.Hash) {
	if rs.currentMap != nil {
		for layerIndex := uint32(0); ; layerIndex++ { //TODO cache layer mapping?
			rowIndex := rs.params.rowIndex(rs.mapIndex, layerIndex, mapValue)
			if rowLength := rs.currentMap.rowLength(rowIndex); rowLength < rs.params.getMaxRowLength(layerIndex) {
				value := rs.params.columnIndex(rs.nextEntry, &mapValue)
				rs.currentMap.addToRow(rowIndex, value)
				rowRoot := rs.mapRowRoots[rowIndex]
				//fmt.Println("addValue rowIndex", rowIndex, "rowRoot", rowRoot, "rowLength", rowLength)
				entryNode := rs.tree.getDescendant(rowRoot, rs.params.progListSubIndex(rowLength/8))
				countNode := rs.tree.getDescendant(rowRoot, ti64(rtiListCount))
				leafPtr := rowLength % 8
				var entryValue, countValue merkle.Value
				if leafPtr != 0 {
					entryValue = rs.tree.getValue(entryNode.index).value
				}
				binary.LittleEndian.PutUint32(entryValue[leafPtr*4:leafPtr*4+4], value)
				leafPtr++
				rowLength++
				rs.tree.setValue(entryNode.index, entryValue, rs.params.filterRowNodeWeight(leafPtr*uint32(rs.params.logMapWidth+7/8)))
				/*if leafPtr == 8 {
					rs.tree.setComplete(entryNode)
				}*/
				binary.LittleEndian.PutUint32(countValue[:4], rowLength)
				countBytes := uint32(1)
				if rowLength >= 256 {
					countBytes = 2
				}
				rs.tree.setValue(countNode.index, countValue, rs.params.filterRowNodeWeight(countBytes))
				break
			}
		}
	}
	rs.advance(1)
}

func (rs *renderState) setNextEntryNode() {
	rs.nextEntryNode = rs.tree.getDescendant(rs.params.treeRoot, rs.params.indexEnrtyRoot(rs.nextEntry)) //TODO optimize this
	//fmt.Println("setNextEntryNode", rs.nextEntryNode)
}

func (rs *renderState) addBlockMeta(blockNumber uint64, blockHash common.Hash, timestamp uint64) {
	if rs.currentMap == nil {
		return
	}
	//fmt.Println("rs.nextEntryNode", rs.nextEntryNode)
	entryMetaRoot := rs.tree.getDescendant(rs.nextEntryNode, ti64(rtiEntryMeta))
	rs.tree.setValue(rs.tree.getDescendant(entryMetaRoot, ti64(rtiBlockMetaBlockNumber)).index, uint64ToValue(blockNumber), rs.params.indexEntryNodeWeight(8))
	rs.tree.setValue(rs.tree.getDescendant(entryMetaRoot, ti64(rtiBlockMetaBlockHash)).index, merkle.Value(blockHash), rs.params.indexEntryNodeWeight(32))
	rs.tree.setValue(rs.tree.getDescendant(entryMetaRoot, ti64(rtiBlockMetaTimestamp)).index, uint64ToValue(timestamp), rs.params.indexEntryNodeWeight(8))
}

func (rs *renderState) addTxMeta(blockNumber uint64, txHash common.Hash, txIndex int, receiptHash common.Hash) {
	if rs.currentMap == nil {
		return
	}
	entryMetaRoot := rs.tree.getDescendant(rs.nextEntryNode, ti64(rtiEntryMeta))
	rs.tree.setValue(rs.tree.getDescendant(entryMetaRoot, ti64(rtiTxMetaBlockNumber)).index, uint64ToValue(uint64(blockNumber)), rs.params.indexEntryNodeWeight(8))
	rs.tree.setValue(rs.tree.getDescendant(entryMetaRoot, ti64(rtiTxMetaTxHash)).index, merkle.Value(txHash), rs.params.indexEntryNodeWeight(32))
	rs.tree.setValue(rs.tree.getDescendant(entryMetaRoot, ti64(rtiTxMetaTxIndex)).index, uint64ToValue(uint64(txIndex)), rs.params.indexEntryNodeWeight(2))
	rs.tree.setValue(rs.tree.getDescendant(entryMetaRoot, ti64(rtiTxMetaReceiptHash)).index, merkle.Value(receiptHash), rs.params.indexEntryNodeWeight(32))
}

func (rs *renderState) addLogEntryAndMeta(log *types.Log, blockNumber uint64, txHash common.Hash, txIndex, logIndex int) {
	if rs.currentMap == nil {
		return
	}
	indexEntryNode := rs.nextEntryNode
	logEntryRoot := rs.tree.getDescendant(indexEntryNode, ti64(rtiLogEntry))
	var address merkle.Value
	copy(address[:20], log.Address[:])
	rs.tree.setValue(rs.tree.getDescendant(logEntryRoot, ti64(rtiLogAddress)).index, address, rs.params.indexEntryNodeWeight(20))
	rs.tree.setValue(rs.tree.getDescendant(logEntryRoot, ti64(rtiLogTopics).gtSub(rtiListCount)).index, uint64ToValue(uint64(len(log.Topics))), rs.params.indexEntryNodeWeight(1))
	for i, topic := range log.Topics {
		rs.tree.setValue(rs.tree.getDescendant(logEntryRoot, ti64(rtiLogTopics).gtSub(rtiListTree).arraySub(uint64(i), 2)).index, merkle.Value(topic), rs.params.indexEntryNodeWeight(32))
	}
	dataChunks := (len(log.Data) + 31) / 32
	logDataRoot := rs.tree.getDescendant(logEntryRoot, ti64(rtiLogData))
	rs.tree.setValue(rs.tree.getDescendant(logDataRoot, ti64(rtiListCount)).index, uint64ToValue(uint64(dataChunks)), rs.params.indexEntryNodeWeight(1))
	for i := range dataChunks {
		var chunk merkle.Value
		start, end := i*32, min((i+1)*32, len(log.Data))
		copy(chunk[:end-start], log.Data[start:end])
		rs.tree.setValue(rs.tree.getDescendant(logDataRoot, rs.params.progListSubIndex(uint32(i))).index, chunk, rs.params.indexEntryNodeWeight(uint32(end-start)))
	}
	entryMetaRoot := rs.tree.getDescendant(indexEntryNode, ti64(rtiEntryMeta))
	rs.tree.setValue(rs.tree.getDescendant(entryMetaRoot, ti64(rtiLogMetaBlockNumber)).index, uint64ToValue(uint64(blockNumber)), rs.params.indexEntryNodeWeight(8))
	rs.tree.setValue(rs.tree.getDescendant(entryMetaRoot, ti64(rtiLogMetaTxHash)).index, merkle.Value(txHash), rs.params.indexEntryNodeWeight(32))
	rs.tree.setValue(rs.tree.getDescendant(entryMetaRoot, ti64(rtiLogMetaTxIndex)).index, uint64ToValue(uint64(txIndex)), rs.params.indexEntryNodeWeight(2))
	rs.tree.setValue(rs.tree.getDescendant(entryMetaRoot, ti64(rtiLogMetaLogIndex)).index, uint64ToValue(uint64(logIndex)), rs.params.indexEntryNodeWeight(2))
}

// if mapRowRoots != nil then assumes that it belongs to the previous map and completes its rows.
func (rs *renderState) advanceMapTree(completeOld, initNew bool) {
	TTadvanceMapTree -= mclock.Now()
	defer func() { TTadvanceMapTree += mclock.Now() }()

	var totalSize int
	for _, s := range rs.tree.subtrees {
		totalSize += len(s.nodeEnc)
	}
	fmt.Println("advanceMapTree", rs.mapIndex, "tree nodes", len(rs.tree.nodes), "subtrees", len(rs.tree.subtrees), "totalSize", totalSize)
	epoch := rs.params.mapEpoch(rs.mapIndex)

	defer func() {
		fmt.Println(" used", rs.tree.debugCountNodes(rootIndex), "free", rs.tree.debugCountFree())
		node := rs.tree.getDescendant(rs.params.treeRoot, ti64(rtiEpochs).arraySub(uint64(epoch), rs.params.logEpochHistory).gtSub(rtiFilterMaps).arraySub(0, rs.params.logMapHeight))
		fmt.Println(" *** row 0:", rs.tree.debugCountNodes(node.index), "used")
		rs.tree.debugPrint(node.index, 1)
		/*node = rs.tree.getDescendant(rs.params.treeRoot, ti64(rtiEpochs).arraySub(uint64(epoch), rs.params.logEpochHistory).gtSub(rtiIndexEntries))
		fmt.Println(" *** index entries:", rs.tree.debugCountNodes(node.index), "used")
		rs.tree.debugPrint(node.index, 1)*/
	}()

	if completeOld != (rs.mapRowRoots != nil) {
		panic("advanceMapTree: completeOld inconsistent with mapRowRoots")
	}
	if !initNew {
		if completeOld {
			fmt.Println("advanceMapTree (complete only)", rs.mapIndex)
			for _, r := range rs.mapRowRoots {
				rs.tree.setComplete(r)
			}
		}
		return
	}

	if completeOld && rs.mapIndex > rs.params.firstEpochMap(epoch) {
		fmt.Println("advanceMapTree (quick)", rs.mapIndex)
		for i, r := range rs.mapRowRoots {
			rs.mapRowRoots[i] = rs.tree.getRightNeighbor(r)
			rs.tree.setValue(rs.tree.getDescendant(rs.mapRowRoots[i], ti64(rtiListCount)).index, merkle.Value{}, rs.params.filterRowNodeWeight(0))
			rs.tree.setComplete(r)
		}
		//rs.tree.debugNodeLevels()
		return
	}

	fmt.Println("advanceMapTree (full)", rs.mapIndex)
	fmRootNode := rs.tree.getDescendant(rs.params.treeRoot, ti64(rtiEpochs).arraySub(uint64(epoch), rs.params.logEpochHistory).gtSub(rtiFilterMaps))
	mapSubIndex := rs.mapIndex - rs.params.firstEpochMap(epoch)
	if !completeOld {
		rs.mapRowRoots = make([]mtNode, rs.params.mapHeight)
	}
	rowSubtreeNode := rs.tree.getDescendant(fmRootNode, gtiRoot.arraySub(0, rs.params.logMapHeight))
	for i, r := range rs.mapRowRoots {
		//fmt.Println(" rowSubtreeNode", i, rowSubtreeNode)
		rs.mapRowRoots[i] = rs.tree.getDescendant(rowSubtreeNode, gtiRoot.arraySub(uint64(mapSubIndex), rs.params.logMapsPerEpoch))
		if i < len(rs.mapRowRoots)-1 {
			rowSubtreeNode = rs.tree.getRightNeighbor(rowSubtreeNode)
		}
		//rs.tree.setValue(rs.tree.getDescendant(rs.mapRowRoots[rowIndex], ti64(rtiListTree)).index, merkle.Value{}, rs.params.filterRowNodeWeight(0))
		rs.tree.setValue(rs.tree.getDescendant(rs.mapRowRoots[i], ti64(rtiListCount)).index, merkle.Value{}, rs.params.filterRowNodeWeight(0))
		if completeOld {
			rs.tree.setComplete(r)
		}
	}
	//rs.tree.debugNodeLevels()

	fmt.Println("TTaddTxAndLogEntries", time.Duration(TTaddTxAndLogEntries+mclock.Now()))
	fmt.Println("TTaddBlockEntry     ", time.Duration(TTaddBlockEntry))
	fmt.Println("TTadvanceMapTree    ", time.Duration(TTadvanceMapTree+mclock.Now()))
	fmt.Println("TTgetDescendant     ", time.Duration(TTgetDescendant))
	fmt.Println("TTtreeHash          ", time.Duration(TTtreeHash))
}

var TTaddTxAndLogEntries,
	TTaddBlockEntry,
	TTadvanceMapTree,
	TTgetDescendant,
	TTtreeHash mclock.AbsTime

func (rs *renderState) advance(count uint64) {
	if rs.currentMap != nil {
		// advance nextEntry pointer
		for range count {
			//fmt.Println("getRightNeighbor", rs.nextEntryNode)
			newEntryNode := rs.tree.getRightNeighbor(rs.nextEntryNode) // needs full reinit at epoch boundary
			rs.tree.setComplete(rs.nextEntryNode)
			rs.nextEntry++
			if rs.nextEntry%1000 == 0 {
				TTtreeHash -= mclock.Now()
				nw := rs.tree.getValue(rootIndex)
				TTtreeHash += mclock.Now()
				if rs.nextEntry%1000000 == 0 {
					fmt.Printf(" root @ %d: 0x%064x   weight: %f\n", rs.nextEntry/1000000, nw.value, nw.weight)
				}
			}
			rs.nextEntryNode = newEntryNode
		}
	} else {
		rs.nextEntry += count
	}
	newMapIndex := uint32(rs.nextEntry >> rs.params.logValuesPerMap)
	if newMapIndex == rs.mapIndex {
		return
	}
	fmt.Println("advance mapIndex", newMapIndex)
	// advance map index
	rs.mapIndex++
	if newMapIndex != rs.mapIndex {
		panic("advance: invalid map index")
	}
	completeOld, initNew := rs.currentMap != nil, rs.renderRange.Includes(rs.mapIndex)
	fmt.Println(" completeOld", completeOld, "initNew", initNew)
	fmt.Println(" advanceMapTree", rs.tree != nil)
	if completeOld {
		xxxParams = rs.params
		rs.tree.verticalNodes = rs.params.newVerticalNodesWriter(rs.mapIndex - 1) //TODO make this more elegant
		/*for i := range rs.params.mapHeight {
			l := rs.currentMap.rowLength(i)
			if l > 8 {
				fmt.Println(" map", rs.mapIndex-1, "row", i, "len", l)
			}
		}*/
		fmt.Println(" vertical node lists:", len(rs.tree.verticalNodes.lists))
	}
	rs.advanceMapTree(completeOld, initNew)
	fmt.Println(" advanceMapTree done")
	if completeOld {
		if !rs.tree.verticalNodes.isComplete() {
			panic("verticalNodesWriter is not complete after completing map")
		}
		fm := rs.currentMap.completed(rs.tree.getStoredSubtrees(), rs.tree.verticalNodes.lists)
		rs.tree.clearStoredSubtrees()
		rs.tree.verticalNodes = nil
		rs.finishedMaps = append(rs.finishedMaps, fm)
		rs.currentMap = nil
	}
	if initNew {
		if !completeOld || rs.mapIndex == rs.params.firstEpochMap(rs.params.mapEpoch(rs.mapIndex)) {
			rs.setNextEntryNode() // next entry pointer at beginning of new epoch
		}
		rs.currentMap = rs.params.newMemoryMap()
	}
}

func (rs *renderState) finished() bool {
	return rs.mapIndex >= rs.renderRange.AfterLast()
}
