// Copyright 2025 The go-ethereum Authors
// This file is part of the go-ethereum library.
//
// The go-ethereum library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-ethereum library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.

package filtermaps

import (
	"sort"
	"sync"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/lru"
	"github.com/ethereum/go-ethereum/core/rawdb"
	"github.com/ethereum/go-ethereum/ethdb"
	"github.com/ethereum/go-ethereum/log"
)

const maxWritesPerBatch = 100000

type mapDatabase struct {
	params *Params
	db     ethdb.KeyValueStore

	lastBlockCache *lru.Cache[uint32, lastBlockOfMap]
	lvPointerCache *lru.Cache[uint64, uint64]
}

func newMapDatabase(params *Params, db ethdb.KeyValueStore) *mapDatabase {
	return &mapStorage{
		params:         params,
		db:             db,
		lastBlockCache: lru.NewCache[uint32, lastBlockOfMap](cachedLastBlocks),
		lvPointerCache: lru.NewCache[uint64, uint64](cachedLvPointers),
	}
}

func (m *mapDatabase) loadMapRange() (valid, dirty rangeSet[uint32], err error) {
	panic("TODO")
}

func (m *mapDatabase) storeMapRange(valid, dirty rangeSet[uint32]) {
	panic("TODO")
}

// getBlockLvPointer returns the starting log value index where the log values
// generated by the given block are located.
//
// Note that this function assumes that the indexer read lock is being held when
// called from outside the indexerLoop goroutine.
func (m *mapDatabase) getBlockLvPointer(blockNumber uint64) (uint64, error) {
	if lvPointer, ok := m.lvPointerCache.Get(blockNumber); ok {
		return lvPointer, nil
	}
	lvPointer, err := rawdb.ReadBlockLvPointer(m.db, blockNumber)
	if err != nil {
		return 0, fmt.Errorf("failed to retrieve log value pointer of block %d: %v", blockNumber, err)
	}
	m.lvPointerCache.Add(blockNumber, lvPointer)
	return lvPointer, nil
}

// storeBlockLvPointer stores the starting log value index where the log values
// generated by the given block are located.
func (m *mapDatabase) storeBlockLvPointer(batch ethdb.Batch, blockNumber, lvPointer uint64) {
	m.lvPointerCache.Add(blockNumber, lvPointer)
	rawdb.WriteBlockLvPointer(batch, blockNumber, lvPointer)
}

// deleteBlockLvPointer deletes the starting log value index where the log values
// generated by the given block are located.
func (m *mapDatabase) deleteBlockLvPointer(batch ethdb.Batch, blockNumber uint64) {
	m.lvPointerCache.Remove(blockNumber)
	rawdb.DeleteBlockLvPointer(batch, blockNumber)
}

// getLastBlockOfMap returns the number and id of the block that generated the
// last log value entry of the given map.
func (m *mapDatabase) getLastBlockOfMap(mapIndex uint32) (uint64, common.Hash, error) {
	if lastBlock, ok := m.lastBlockCache.Get(mapIndex); ok {
		return lastBlock.number, lastBlock.id, nil
	}
	number, id, err := rawdb.ReadFilterMapLastBlock(m.db, mapIndex)
	if err != nil {
		return 0, common.Hash{}, fmt.Errorf("failed to retrieve last block of map %d: %v", mapIndex, err)
	}
	m.lastBlockCache.Add(mapIndex, lastBlockOfMap{number: number, id: id})
	return number, id, nil
}

// storeLastBlockOfMap stores the number of the block that generated the last
// log value entry of the given map.
func (m *mapDatabase) storeLastBlockOfMap(batch ethdb.Batch, mapIndex uint32, number uint64, id common.Hash) {
	m.lastBlockCache.Add(mapIndex, lastBlockOfMap{number: number, id: id})
	rawdb.WriteFilterMapLastBlock(batch, mapIndex, number, id)
}

// deleteLastBlockOfMap deletes the number of the block that generated the last
// log value entry of the given map.
func (m *mapDatabase) deleteLastBlockOfMap(batch ethdb.Batch, mapIndex uint32) {
	m.lastBlockCache.Remove(mapIndex)
	rawdb.DeleteFilterMapLastBlock(batch, mapIndex)
}

func (m *mapDatabase) deleteEpoch(epoch uint32, stopCallback func() bool) (bool, error) {
	panic("TODO")
}

type writePatterItem struct {
	mapIndex, dbLayer uint32
	keepRows          []uint32 // keep existing rows of layer group
}

func (m *mapDatabase) writeMaps(writeMaps, deleteMaps, keepMaps rangeSet[uint32], maps map[uint32]*finishedMap, stopCallback func() bool) (bool, error) {
	var writePattern []writePatterItem
	updateMaps := writeMaps.union(deleteMaps)
	for dbLayer, groupSize := range m.params.rowGroupSize {
		updateGroups := updateMaps
		if groupSize > 1 {
			updateRb := make(rangeBoundaries[uint32], 0, len(updateMaps)*2)
			for _, r := range updateMaps {
				first, last := r.First()/groupSize, r.Last()/groupSize
				updateRb.add(common.NewRange[uint32](first, last+1-first), 1)
			}
			updateGroups = updateRb.makeSet(1)
		}
		for i := range updateGroups.iter() {
			var keepRows []uint32
			if groupSize > 1 {
				for j := range groupSize {
					if keepMaps.includes(i*groupSize + j) {
						keepRows = append(keepRows, j)
					}
				}
			}
			writePattern = append(writePattern, writePatterItem{
				mapIndex: i * groupSize,
				dbLayer:  uint32(dbLayer),
				keepRows: keepRows,
			})
		}
	}
	sort.Slice(writePattern, func(i, j int) bool {
		return writePattern[i].mapIndex < writePattern[j].mapIndex ||
			(writePattern[i].mapIndex == writePattern[j].mapIndex && writePattern[i].dbLayer < writePattern[j].dbLayer)
	})
}

func (m *mapStorage) processWriteCycle(stopCallback func() bool) (bool, error) {
	if m.deleteAll {
		return m.deleteEpoch(m.epoch, stopCallback)
	}
	batch := m.db.NewBatch()
	rowsPerBatch := uint32(max(maxWritesPerBatch/len(writePattern), 1))
	for rowIndex := range m.params.mapHeight {
		if err := m.writeRowUpdates(batch, rowIndex); err != nil {
			return false, err
		}
		if rowIndex%rowsPerBatch == rowsPerBatch-1 {
			if err := batch.Write(); err != nil {
				return false, err
			}
			if stopCallback() {
				return false, nil
			}
			batch = m.db.NewBatch()
		}
	}
	if err := batch.Write(); err != nil {
		return false, err
	}
	return true, nil
}

func (m *mapStorage) writeRowUpdates(batch ethdb.Batch, rowIndex uint32) error {
	for _, w := range writePattern {
		if groupSize := m.params.rowGroupSize[w.dbLayer]; groupSize == 1 {
			var row FilterRow
			if fm := m.writeMaps[w.mapIndex]; fm != nil {
				row = fm.getRow(rowIndex, m.params.maxRowLength[w.dbLayer])
			}
			var from uint32
			if w.dbLayer > 0 {
				from = m.params.maxRowLength[w.dbLayer-1]
			}
			if uint32(len(row)) > from {
				row = row[from:]
			} else {
				row = nil
			}
			rawdb.WriteFilterMapSingleRow(batch, m.params.mapRowIndex(w.mapIndex, rowIndex), w.dbLayer, row, m.params.logMapWidth)
		} else {
			rows := make([][]uint32, groupSize)
			if w.keepRows != nil {
				oldRows, err := rawdb.ReadFilterMapRowGroup(m.db, m.params.mapRowIndex(w.mapIndex, rowIndex), w.dbLayer, groupSize, m.params.logMapWidth)
				if err != nil {
					return err
				}
				for _, i := range w.keepRows {
					rows[i] = oldRows[i]
				}
			}
			var from uint32
			if w.dbLayer > 0 {
				from = m.params.maxRowLength[w.dbLayer-1]
			}
			to := m.params.maxRowLength[w.dbLayer]
			for i := range groupSize {
				if fm := m.writeMaps[w.mapIndex+i]; fm != nil {
					if row := fm.getRow(rowIndex, to); uint32(len(row)) > from {
						rows[i] = row[from:]
					}
				}
			}
			rawdb.WriteFilterMapRowGroup(batch, m.params.mapRowIndex(w.mapIndex, rowIndex), w.dbLayer, rows, m.params.logMapWidth)
		}
	}
	return nil
}
