// Copyright 2025 The go-ethereum Authors
// This file is part of the go-ethereum library.
//
// The go-ethereum library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-ethereum library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.

package filtermaps

import (
	"fmt"
	"sort"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/lru"
	"github.com/ethereum/go-ethereum/core/rawdb"
	"github.com/ethereum/go-ethereum/ethdb"
)

const maxWritesPerBatch = 100000

type mapDatabase struct {
	params *Params
	db     ethdb.KeyValueStore

	lastBlockCache *lru.Cache[uint32, lastBlockOfMap]
	lvPointerCache *lru.Cache[uint64, uint64]
}

func newMapDatabase(params *Params, db ethdb.KeyValueStore) *mapDatabase {
	return &mapDatabase{
		params:         params,
		db:             db,
		lastBlockCache: lru.NewCache[uint32, lastBlockOfMap](cachedLastBlocks),
		lvPointerCache: lru.NewCache[uint64, uint64](cachedLvPointers),
	}
}

func (m *mapDatabase) loadMapRange() (valid, dirty rangeSet[uint32], err error) {
	panic("TODO")
}

func (m *mapDatabase) storeMapRange(valid, dirty rangeSet[uint32]) {
	panic("TODO")
}

// getBlockLvPointer returns the starting log value index where the log values
// generated by the given block are located.
//
// Note that this function assumes that the indexer read lock is being held when
// called from outside the indexerLoop goroutine.
func (m *mapDatabase) getBlockLvPointer(blockNumber uint64) (uint64, error) {
	if lvPointer, ok := m.lvPointerCache.Get(blockNumber); ok {
		return lvPointer, nil
	}
	lvPointer, err := rawdb.ReadBlockLvPointer(m.db, blockNumber)
	if err != nil {
		return 0, fmt.Errorf("failed to retrieve log value pointer of block %d: %v", blockNumber, err)
	}
	m.lvPointerCache.Add(blockNumber, lvPointer)
	return lvPointer, nil
}

// storeBlockLvPointer stores the starting log value index where the log values
// generated by the given block are located.
func (m *mapDatabase) storeBlockLvPointer(batch ethdb.Batch, blockNumber, lvPointer uint64) {
	m.lvPointerCache.Add(blockNumber, lvPointer)
	rawdb.WriteBlockLvPointer(batch, blockNumber, lvPointer)
}

// deleteBlockLvPointer deletes the starting log value index where the log values
// generated by the given block are located.
func (m *mapDatabase) deleteBlockLvPointer(batch ethdb.Batch, blockNumber uint64) {
	m.lvPointerCache.Remove(blockNumber)
	rawdb.DeleteBlockLvPointer(batch, blockNumber)
}

// getLastBlockOfMap returns the number and id of the block that generated the
// last log value entry of the given map.
func (m *mapDatabase) getLastBlockOfMap(mapIndex uint32) (uint64, common.Hash, error) {
	if lastBlock, ok := m.lastBlockCache.Get(mapIndex); ok {
		return lastBlock.number, lastBlock.id, nil
	}
	number, id, err := rawdb.ReadFilterMapLastBlock(m.db, mapIndex)
	if err != nil {
		return 0, common.Hash{}, fmt.Errorf("failed to retrieve last block of map %d: %v", mapIndex, err)
	}
	m.lastBlockCache.Add(mapIndex, lastBlockOfMap{number: number, id: id})
	return number, id, nil
}

// storeLastBlockOfMap stores the number of the block that generated the last
// log value entry of the given map.
func (m *mapDatabase) storeLastBlockOfMap(batch ethdb.Batch, mapIndex uint32, number uint64, id common.Hash) {
	m.lastBlockCache.Add(mapIndex, lastBlockOfMap{number: number, id: id})
	rawdb.WriteFilterMapLastBlock(batch, mapIndex, number, id)
}

// deleteLastBlockOfMap deletes the number of the block that generated the last
// log value entry of the given map.
func (m *mapDatabase) deleteLastBlockOfMap(batch ethdb.Batch, mapIndex uint32) {
	m.lastBlockCache.Remove(mapIndex)
	rawdb.DeleteFilterMapLastBlock(batch, mapIndex)
}

func (m *mapDatabase) deleteEpoch(epoch uint32, stopCallback func() bool) (bool, error) {
	panic("TODO")
}

func (m *mapDatabase) reset(stopCallback func() bool) bool {
	panic("TODO") // safe delete with logs
}

func (m *mapDatabase) deletePointers(deleteMaps common.Range[uint32], stopCallback func() bool) error {
	var firstBlock, afterLastBlock uint64
	if deleteMaps.First() > 0 {
		lb, _, err := m.getLastBlockOfMap(deleteMaps.First() - 1)
		if err != nil {
			return false, err
		}
		firstBlock = lb + 1
	}
	if deleteMaps.AfterLast() < math.MaxUint32 { //TODO change map index to uint64?
		lb, _, err := m.getLastBlockOfMap(deleteMaps.Last())
		if err != nil {
			return false, err
		}
		afterLastBlock = lb
	} else {
		afterLastBlock = math.MaxUint64
	}
	if afterLastBlock > firstBlock {
		blockRange := common.NewRange[uint64](firstBlock, afterLastBlock-firstBlock) // keep last pointer
		if err := rawdb.DeleteBlockLvPointers(m.db, blockRange, m.hashScheme, stopCallback); err != nil {
			return err
		}
	}
	if deleteMaps.Count() > 1 {
		mapRange := common.NewRange[uint64](deleteMaps.First(), deleteMaps.Count()-1) // keep last pointer
		if err := rawdb.DeleteFilterMapLastBlocks(m.db, mapRange, m.hashScheme, stopCallback); err != nil {
			return err
		}
	}
	return nil
}

type writePatterItem struct {
	mapIndex, dbLayer uint32
	keepRows          common.Range[uint32] // keep existing rows of layer group
	dirty             bool                 // there are dirty entries in the layer group
}

func (m *mapDatabase) writeMaps(writeMaps, deleteMaps, keepMaps rangeSet[uint32], maps map[uint32]*finishedMap, stopCallback func() bool) (bool, error) {
	writePattern := m.makeWritePattern(writeMaps, deleteMaps, keepMaps)
	batch := m.db.NewBatch()
	rowsPerBatch := uint32(max(maxWritesPerBatch/len(writePattern), 1))
	var (
		batchCnt uint32
		writeErr error
	)
	checkWrite := func() bool {
		batchCnt++
		if batchCnt >= rowsPerBatch {
			if writeErr = batch.Write(); writeErr != nil {
				return true
			}
			if stopCallback() {
				return true
			}
			batch = m.db.NewBatch()
			batchCnt = 0
		}
		return false
	}

	for rowIndex := range m.params.mapHeight {
		if err := m.writeRowUpdates(batch, writePattern, maps, rowIndex); err != nil {
			return false, err
		}
		if checkWrite() {
			return false, writeErr
		}
	}
	for mapIndex := range writeMaps.iter() {
		fm := maps[mapIndex]
		rawdb.WriteFilterMapLastBlock(batch, mapIndex, fm.lastBlock.number, fm.lastBlock.id)
		if checkWrite() {
			return false, writeErr
		}
		for i, lvPtr := range fm.blockPtrs {
			rawdb.WriteBlockLvPointer(batch, fm.firstBlock()+uint64(i), lvPtr)
			if checkWrite() {
				return false, writeErr
			}
		}
	}
	if err := batch.Write(); err != nil {
		return false, err
	}
	return true, nil
}

func (m *mapDatabase) makeWritePattern(writeMaps, deleteMaps, keepMaps rangeSet[uint32]) (writePattern []writePatterItem) {
	updateMaps := writeMaps.union(deleteMaps)
	for dbLayer, groupSize := range m.params.rowGroupSize {
		updateGroups := updateMaps
		if groupSize > 1 {
			updateRb := make(rangeBoundaries[uint32], 0, len(updateMaps)*2)
			for _, r := range updateMaps {
				first, last := r.First()/groupSize, r.Last()/groupSize
				updateRb.add(common.NewRange[uint32](first, last+1-first), 1)
			}
			updateGroups = updateRb.makeSet(1)
		}
		for i := range updateGroups.iter() {
			var keepRows []uint32
			if groupSize > 1 {
				for j := range groupSize {
					if keepMaps.includes(i*groupSize + j) {
						keepRows = append(keepRows, j)
					}
				}
			}
			writePattern = append(writePattern, writePatterItem{
				mapIndex: i * groupSize,
				dbLayer:  uint32(dbLayer),
				keepRows: keepRows,
			})
		}
	}
	sort.Slice(writePattern, func(i, j int) bool {
		return writePattern[i].mapIndex < writePattern[j].mapIndex ||
			(writePattern[i].mapIndex == writePattern[j].mapIndex && writePattern[i].dbLayer < writePattern[j].dbLayer)
	})
	return
}

func (m *mapDatabase) writeRowUpdates(batch ethdb.Batch, writePattern []writePatterItem, maps map[uint32]*finishedMap, rowIndex uint32) error {
	for _, w := range writePattern {
		if groupSize := m.params.rowGroupSize[w.dbLayer]; groupSize == 1 {
			var row FilterRow
			if fm := maps[w.mapIndex]; fm != nil {
				row = fm.getRow(rowIndex, m.params.maxRowLength[w.dbLayer])
			}
			var from uint32
			if w.dbLayer > 0 {
				from = m.params.maxRowLength[w.dbLayer-1]
			}
			if uint32(len(row)) > from {
				row = row[from:]
			} else {
				row = nil
			}
			if len(row) > 0 || w.dirty {
				rawdb.WriteFilterMapSingleRow(batch, m.params.mapRowIndex(w.mapIndex, rowIndex), w.dbLayer, row, m.params.logMapWidth)
			}
		} else {
			rows := make([][]uint32, groupSize)
			writeGroup := w.dirty
			if w.keepRows.Count() > 0 {
				oldRows, err := rawdb.ReadFilterMapRowGroup(m.db, m.params.mapRowIndex(w.mapIndex, rowIndex), w.dbLayer, groupSize, m.params.logMapWidth)
				if err != nil {
					return err
				}
				for _, i := range w.keepRows.Iter() {
					rows[i] = oldRows[i]
				}

			}
			var from uint32
			if w.dbLayer > 0 {
				from = m.params.maxRowLength[w.dbLayer-1]
			}
			to := m.params.maxRowLength[w.dbLayer]
			for i := range groupSize {
				if fm := maps[w.mapIndex+i]; fm != nil {
					if row := fm.getRow(rowIndex, to); uint32(len(row)) > from {
						rows[i] = row[from:]
						writeGroup = true
					}
				}
			}
			if writeGroup {
				rawdb.WriteFilterMapRowGroup(batch, m.params.mapRowIndex(w.mapIndex, rowIndex), w.dbLayer, rows, m.params.logMapWidth)
			}
		}
	}
	return nil
}
