// Copyright 2025 The go-ethereum Authors
// This file is part of the go-ethereum library.
//
// The go-ethereum library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-ethereum library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.

package filtermaps

import (
	"errors"
	"fmt"
	"math"
	"sort"
	"time"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/lru"
	"github.com/ethereum/go-ethereum/core/rawdb"
	"github.com/ethereum/go-ethereum/ethdb"
	"github.com/ethereum/go-ethereum/log"
)

const maxWritesPerBatch = 100000

type mapDatabase struct {
	params     *Params
	db         ethdb.KeyValueStore
	hashScheme bool

	lastBlockCache *lru.Cache[uint32, lastBlockOfMap]
	lvPointerCache *lru.Cache[uint64, uint64]
}

func newMapDatabase(params *Params, db ethdb.KeyValueStore, hashScheme bool) *mapDatabase {
	return &mapDatabase{
		params:         params,
		db:             db,
		hashScheme:     hashScheme,
		lastBlockCache: lru.NewCache[uint32, lastBlockOfMap](cachedLastBlocks),
		lvPointerCache: lru.NewCache[uint64, uint64](cachedLvPointers),
	}
}

func (m *mapDatabase) loadMapRange() (valid, dirty rangeSet[uint32], err error) {
	panic("TODO")
}

func (m *mapDatabase) storeMapRange(valid, dirty rangeSet[uint32]) {
	panic("TODO")
}

// getBlockLvPointer returns the starting log value index where the log values
// generated by the given block are located.
//
// Note that this function assumes that the indexer read lock is being held when
// called from outside the indexerLoop goroutine.
func (m *mapDatabase) getBlockLvPointer(blockNumber uint64) (uint64, error) {
	if lvPointer, ok := m.lvPointerCache.Get(blockNumber); ok {
		return lvPointer, nil
	}
	lvPointer, err := rawdb.ReadBlockLvPointer(m.db, blockNumber)
	if err != nil {
		return 0, fmt.Errorf("failed to retrieve log value pointer of block %d: %v", blockNumber, err)
	}
	m.lvPointerCache.Add(blockNumber, lvPointer)
	return lvPointer, nil
}

// storeBlockLvPointer stores the starting log value index where the log values
// generated by the given block are located.
func (m *mapDatabase) storeBlockLvPointer(batch ethdb.Batch, blockNumber, lvPointer uint64) {
	m.lvPointerCache.Add(blockNumber, lvPointer)
	rawdb.WriteBlockLvPointer(batch, blockNumber, lvPointer)
}

// deleteBlockLvPointer deletes the starting log value index where the log values
// generated by the given block are located.
func (m *mapDatabase) deleteBlockLvPointer(batch ethdb.Batch, blockNumber uint64) {
	m.lvPointerCache.Remove(blockNumber)
	rawdb.DeleteBlockLvPointer(batch, blockNumber)
}

// getLastBlockOfMap returns the number and id of the block that generated the
// last log value entry of the given map.
func (m *mapDatabase) getLastBlockOfMap(mapIndex uint32) (uint64, common.Hash, error) {
	if lastBlock, ok := m.lastBlockCache.Get(mapIndex); ok {
		return lastBlock.number, lastBlock.id, nil
	}
	number, id, err := rawdb.ReadFilterMapLastBlock(m.db, mapIndex)
	if err != nil {
		return 0, common.Hash{}, fmt.Errorf("failed to retrieve last block of map %d: %v", mapIndex, err)
	}
	m.lastBlockCache.Add(mapIndex, lastBlockOfMap{number: number, id: id})
	return number, id, nil
}

// storeLastBlockOfMap stores the number of the block that generated the last
// log value entry of the given map.
func (m *mapDatabase) storeLastBlockOfMap(batch ethdb.Batch, mapIndex uint32, number uint64, id common.Hash) {
	m.lastBlockCache.Add(mapIndex, lastBlockOfMap{number: number, id: id})
	rawdb.WriteFilterMapLastBlock(batch, mapIndex, number, id)
}

// deleteLastBlockOfMap deletes the number of the block that generated the last
// log value entry of the given map.
func (m *mapDatabase) deleteLastBlockOfMap(batch ethdb.Batch, mapIndex uint32) {
	m.lastBlockCache.Remove(mapIndex)
	rawdb.DeleteFilterMapLastBlock(batch, mapIndex)
}

func (m *mapDatabase) deleteEpochRows(epoch uint32, stopCallback func() bool) (bool, error) {
	deleteFn := func(db ethdb.KeyValueStore, hashScheme bool, stopCb func(bool) bool) error {
		first := m.params.mapRowIndex(epoch<<m.params.logMapsPerEpoch, 0)
		afterLast := m.params.mapRowIndex((epoch+1)<<m.params.logMapsPerEpoch, 0)
		return rawdb.DeleteFilterMapRows(db, common.NewRange(first, afterLast-first), hashScheme, stopCb)
	}
	action := fmt.Sprintf("Deleting epoch #%d", epoch)
	if err := m.safeDeleteWithLogs(deleteFn, action, stopCallback); err != rawdb.ErrDeleteRangeInterrupted {
		return err == nil, err
	}
	return false, nil
}

func (m *mapDatabase) reset(stopCallback func() bool) (bool, error) {
	if err := m.safeDeleteWithLogs(rawdb.DeleteFilterMapsDb, "Resetting log index database", stopCallback); err != rawdb.ErrDeleteRangeInterrupted {
		return err == nil, err
	}
	return false, nil
}

func (m *mapDatabase) deletePointers(deleteMaps common.Range[uint32], stopCallback func() bool) error {
	var firstBlock, afterLastBlock uint64
	if deleteMaps.First() > 0 {
		lb, _, err := m.getLastBlockOfMap(deleteMaps.First() - 1)
		if err != nil {
			return err
		}
		firstBlock = lb + 1
	}
	if deleteMaps.AfterLast() < math.MaxUint32 { //TODO change map index to uint64?
		lb, _, err := m.getLastBlockOfMap(deleteMaps.Last())
		if err != nil {
			return err
		}
		afterLastBlock = lb
	} else {
		afterLastBlock = math.MaxUint64
	}
	if afterLastBlock > firstBlock {
		m.lvPointerCache.Purge()
		blockRange := common.NewRange[uint64](firstBlock, afterLastBlock-firstBlock) // keep last pointer
		if err := rawdb.DeleteBlockLvPointers(m.db, blockRange, m.hashScheme, func(bool) bool { return stopCallback() }); err != nil {
			return err
		}
	}
	if deleteMaps.Count() > 1 {
		m.lastBlockCache.Purge()
		mapRange := common.NewRange[uint32](deleteMaps.First(), deleteMaps.Count()-1) // keep last pointer
		if err := rawdb.DeleteFilterMapLastBlocks(m.db, mapRange, m.hashScheme, func(bool) bool { return stopCallback() }); err != nil {
			return err
		}
	}
	return nil
}

type writePatterItem struct {
	mapIndex, dbLayer uint32
	valid             common.Range[uint32] // keep existing rows of layer group
	dirty             bool                 // there are dirty entries in the layer group
}

// dirty: before setting write range to dirty
func (m *mapDatabase) writeMaps(writeMaps, valid, dirty common.Range[uint32], maps map[uint32]*finishedMap, stopCallback func() bool) (bool, error) {
	writePattern := m.makeWritePattern(writeMaps, valid, dirty)
	batch := m.db.NewBatch()
	rowsPerBatch := uint32(max(maxWritesPerBatch/len(writePattern), 1))
	var (
		batchCnt uint32
		writeErr error
	)
	checkStopOrCommit := func() bool {
		batchCnt++
		if batchCnt >= rowsPerBatch {
			if writeErr = batch.Write(); writeErr != nil {
				return true
			}
			if stopCallback() {
				return true
			}
			batch = m.db.NewBatch()
			batchCnt = 0
		}
		return false
	}

	for rowIndex := range m.params.mapHeight {
		if err := m.writeRowUpdates(batch, writePattern, maps, rowIndex); err != nil {
			return false, err
		}
		if checkStopOrCommit() {
			return false, writeErr
		}
	}
	for mapIndex := range writeMaps.Iter() {
		fm := maps[mapIndex]
		rawdb.WriteFilterMapLastBlock(batch, mapIndex, fm.lastBlock.number, fm.lastBlock.id)
		if checkStopOrCommit() {
			return false, writeErr
		}
		for i, lvPtr := range fm.blockPtrs {
			rawdb.WriteBlockLvPointer(batch, fm.firstBlock()+uint64(i), lvPtr)
			if checkStopOrCommit() {
				return false, writeErr
			}
		}
	}
	if err := batch.Write(); err != nil {
		return false, err
	}
	return true, nil
}

func (m *mapDatabase) makeWritePattern(writeMaps, valid, dirty common.Range[uint32]) (writePattern []writePatterItem) {
	for dbLayer, groupSize := range m.params.rowGroupSize {
		updateRange := dirty.Union(writeMaps)
		firstGroup, lastGroup := updateRange.First()/groupSize, updateRange.Last()/groupSize
		for i := firstGroup; i <= lastGroup; i++ {
			groupRange := common.NewRange[uint32](i*groupSize, groupSize)
			writePattern = append(writePattern, writePatterItem{
				mapIndex: i * groupSize,
				dbLayer:  uint32(dbLayer),
				valid:    valid.Intersection(groupRange),
				dirty:    !dirty.Intersection(groupRange).IsEmpty(),
			})
		}
	}
	sort.Slice(writePattern, func(i, j int) bool {
		return writePattern[i].mapIndex < writePattern[j].mapIndex ||
			(writePattern[i].mapIndex == writePattern[j].mapIndex && writePattern[i].dbLayer < writePattern[j].dbLayer)
	})
	return
}

func (m *mapDatabase) writeRowUpdates(batch ethdb.Batch, writePattern []writePatterItem, maps map[uint32]*finishedMap, rowIndex uint32) error {
	for _, w := range writePattern {
		if groupSize := m.params.rowGroupSize[w.dbLayer]; groupSize == 1 {
			var row FilterRow
			if fm := maps[w.mapIndex]; fm != nil {
				row = fm.getRow(rowIndex, m.params.maxRowLength[w.dbLayer])
			}
			var from uint32
			if w.dbLayer > 0 {
				from = m.params.maxRowLength[w.dbLayer-1]
			}
			if uint32(len(row)) > from {
				row = row[from:]
			} else {
				row = nil
			}
			if len(row) > 0 || w.dirty {
				rawdb.WriteFilterMapSingleRow(batch, m.params.mapRowIndex(w.mapIndex, rowIndex), w.dbLayer, row, m.params.logMapWidth)
			}
		} else {
			rows := make([][]uint32, groupSize)
			writeGroup := w.dirty
			if w.valid.Count() > 0 {
				oldRows, err := rawdb.ReadFilterMapRowGroup(m.db, m.params.mapRowIndex(w.mapIndex, rowIndex), w.dbLayer, groupSize, m.params.logMapWidth)
				if err != nil {
					return err
				}
				for mapIndex := range w.valid.Iter() {
					rows[mapIndex-w.mapIndex] = oldRows[mapIndex-w.mapIndex]
				}

			}
			var from uint32
			if w.dbLayer > 0 {
				from = m.params.maxRowLength[w.dbLayer-1]
			}
			to := m.params.maxRowLength[w.dbLayer]
			for i := range groupSize {
				if fm := maps[w.mapIndex+i]; fm != nil {
					if row := fm.getRow(rowIndex, to); uint32(len(row)) > from {
						rows[i] = row[from:]
						writeGroup = true
					}
				}
			}
			if writeGroup {
				rawdb.WriteFilterMapRowGroup(batch, m.params.mapRowIndex(w.mapIndex, rowIndex), w.dbLayer, rows, m.params.logMapWidth)
			}
		}
	}
	return nil
}

// safeDeleteWithLogs is a wrapper for a function that performs a safe range
// delete operation using rawdb.SafeDeleteRange. It emits log messages if the
// process takes long enough to call the stop callback.
func (m *mapDatabase) safeDeleteWithLogs(deleteFn func(db ethdb.KeyValueStore, hashScheme bool, stopCb func(bool) bool) error, action string, stopCb func() bool) error {
	var (
		start          = time.Now()
		logPrinted     bool
		lastLogPrinted = start
	)
	switch err := deleteFn(m.db, m.hashScheme, func(deleted bool) bool {
		if deleted && !logPrinted || time.Since(lastLogPrinted) > time.Second*10 {
			log.Info(action+" in progress...", "elapsed", common.PrettyDuration(time.Since(start)))
			logPrinted, lastLogPrinted = true, time.Now()
		}
		return stopCb()
	}); {
	case err == nil:
		if logPrinted {
			log.Info(action+" finished", "elapsed", common.PrettyDuration(time.Since(start)))
		}
		return nil
	case errors.Is(err, rawdb.ErrDeleteRangeInterrupted):
		log.Warn(action+" interrupted", "elapsed", common.PrettyDuration(time.Since(start)))
		return err
	default:
		log.Error(action+" failed", "error", err)
		return err
	}
}

// removeBloomBits removes old bloom bits data from the database.
func (m *mapDatabase) removeBloomBits(stopCb func() bool) {
	m.safeDeleteWithLogs(rawdb.DeleteBloomBitsDb, "Removing old bloom bits database", stopCb)
}
