// Copyright 2024 The go-ethereum Authors
// This file is part of the go-ethereum library.
//
// The go-ethereum library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-ethereum library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.

package filtermaps

import (
	"context"
	"fmt"
	"slices"
	"time"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/lru"
	"github.com/ethereum/go-ethereum/core/types"
)

// FilterMapsMatcherBackend implements MatcherBackend.
type FilterMapsMatcherBackend struct {
	f *FilterMaps

	// these fields should be accessed under f.matchersLock mutex.
	validBlocks common.Range[uint64]
	syncCh      chan SyncRange
}

// NewMatcherBackend returns a FilterMapsMatcherBackend after registering it in
// the active matcher set.
// Note that Close should always be called when the matcher is no longer used.
func (f *FilterMaps) NewMatcherBackend() *FilterMapsMatcherBackend {
	f.indexLock.RLock()
	f.matchersLock.Lock()
	defer func() {
		f.matchersLock.Unlock()
		f.indexLock.RUnlock()
	}()

	fm := &FilterMapsMatcherBackend{f: f}
	if f.indexedRange.initialized {
		fm.validBlocks = f.indexedRange.blocks
	}
	f.matchers[fm] = struct{}{}
	return fm
}

// GetParams returns the filtermaps parameters.
// GetParams implements MatcherBackend.
func (fm *FilterMapsMatcherBackend) GetParams() *Params {
	return &fm.f.Params
}

// Close removes the matcher from the set of active matchers and ensures that
// any SyncLogIndex calls are cancelled.
// Close implements MatcherBackend.
func (fm *FilterMapsMatcherBackend) Close() {
	fm.f.matchersLock.Lock()
	defer fm.f.matchersLock.Unlock()

	delete(fm.f.matchers, fm)
}

type gfmrKey struct {
	mapIndex, rowIndex uint32
	baseLayerOnly      bool
}

type gfmrVal struct {
	data   FilterRow
	stored time.Time
}

type gblpVal struct {
	ptr    uint64
	stored time.Time
}

type glbiPos struct {
	blockNumber uint64
	txi, index  uint
}

type glbiVal struct {
	pos    glbiPos
	stored time.Time
}

type mbTestCaches struct {
	gfmrCache *lru.Cache[gfmrKey, gfmrVal]
	gblpCache *lru.Cache[uint64, gblpVal]
	glbiCache *lru.Cache[uint64, glbiVal]
}

func (m *mbTestCaches) init() {
	m.gfmrCache = lru.NewCache[gfmrKey, gfmrVal](10000000)
	m.gblpCache = lru.NewCache[uint64, gblpVal](10000000)
	m.glbiCache = lru.NewCache[uint64, glbiVal](10000000)
}

// GetFilterMapRow returns the given row of the given map. If the row is empty
// then a non-nil zero length row is returned. If baseLayerOnly is true then
// only the first baseRowLength entries of the row are guaranteed to be
// returned.
// Note that the returned slices should not be modified, they should be copied
// on write.
// GetFilterMapRow implements MatcherBackend.
func (fm *FilterMapsMatcherBackend) GetFilterMapRow(ctx context.Context, mapIndex, rowIndex uint32, baseLayerOnly bool) (FilterRow, error) {
	fm.f.indexLock.RLock()
	defer fm.f.indexLock.RUnlock()

	res, err := fm.f.getFilterMapRow(mapIndex, rowIndex, baseLayerOnly)
	if err != nil {
		return nil, err
	}
	key := gfmrKey{mapIndex, rowIndex, baseLayerOnly}
	if v, ok := fm.f.mbTestCaches.gfmrCache.Get(key); ok && (len(res) < len(v.data) || !slices.Equal(res[:len(v.data)], v.data)) {
		fmt.Println("*** gfmr diff", key, time.Since(v.stored))
		fmt.Println("  stored:", v.data)
		fmt.Println(" current:", res)
	}
	fm.f.mbTestCaches.gfmrCache.Add(key, gfmrVal{slices.Clone(res), time.Now()})
	return res, nil
}

// GetBlockLvPointer returns the starting log value index where the log values
// generated by the given block are located. If blockNumber is beyond the current
// head then the first unoccupied log value index is returned.
// GetBlockLvPointer implements MatcherBackend.
func (fm *FilterMapsMatcherBackend) GetBlockLvPointer(ctx context.Context, blockNumber uint64) (uint64, error) {
	fm.f.indexLock.RLock()
	defer fm.f.indexLock.RUnlock()

	res, err := fm.f.getBlockLvPointer(blockNumber)
	if err != nil {
		return 0, err
	}
	if v, ok := fm.f.mbTestCaches.gblpCache.Get(blockNumber); ok && res != v.ptr {
		fmt.Println("*** gblp diff", blockNumber, time.Since(v.stored))
		fmt.Println("  stored:", v.ptr)
		fmt.Println(" current:", res)
	}
	fm.f.mbTestCaches.gblpCache.Add(blockNumber, gblpVal{res, time.Now()})
	return res, nil
}

// GetLogByLvIndex returns the log at the given log value index.
// Note that this function assumes that the log index structure is consistent
// with the canonical chain at the point where the given log value index points.
// If this is not the case then an invalid result may be returned or certain
// logs might not be returned at all.
// No error is returned though because of an inconsistency between the chain and
// the log index. It is the caller's responsibility to verify this consistency
// using SyncLogIndex and re-process certain blocks if necessary.
// GetLogByLvIndex implements MatcherBackend.
func (fm *FilterMapsMatcherBackend) GetLogByLvIndex(ctx context.Context, lvIndex uint64) (*types.Log, error) {
	fm.f.indexLock.RLock()
	defer fm.f.indexLock.RUnlock()

	res, err := fm.f.getLogByLvIndex(lvIndex)
	if err != nil {
		return nil, err
	}
	var pos glbiPos
	if res != nil {
		pos.blockNumber = res.BlockNumber
		pos.txi = res.TxIndex
		pos.index = res.Index
	}
	if v, ok := fm.f.mbTestCaches.glbiCache.Get(lvIndex); ok && pos != v.pos {
		fmt.Println("*** glbi diff", lvIndex, time.Since(v.stored))
		fmt.Println("  stored:", v.pos)
		fmt.Println(" current:", pos)
	}
	fm.f.mbTestCaches.glbiCache.Add(lvIndex, glbiVal{pos, time.Now()})
	return res, nil
}

// synced signals to the matcher that has triggered a synchronisation that it
// has been finished and the log index is consistent with the chain head passed
// as a parameter.
// Note that if the log index head was far behind the chain head then it might not
// be synced up to the given head in a single step. Still, the latest chain head
// should be passed as a parameter and the existing log index should be consistent
// with that chain.
func (fm *FilterMapsMatcherBackend) synced() {
	fm.f.indexLock.RLock()
	fm.f.matchersLock.Lock()
	defer func() {
		fm.f.matchersLock.Unlock()
		fm.f.indexLock.RUnlock()
	}()

	indexedBlocks := fm.f.indexedRange.blocks
	if !fm.f.indexedRange.headIndexed && !indexedBlocks.IsEmpty() {
		indexedBlocks.SetAfterLast(indexedBlocks.Last()) // remove partially indexed last block
	}
	fm.syncCh <- SyncRange{
		IndexedView:   fm.f.indexedView,
		ValidBlocks:   fm.validBlocks,
		IndexedBlocks: indexedBlocks,
	}
	fm.validBlocks = indexedBlocks
	fm.syncCh = nil
}

// SyncLogIndex ensures that the log index is consistent with the current state
// of the chain and is synced up to the current head. It blocks until this state
// is achieved or the context is cancelled.
// If successful, it returns a SyncRange that contains the latest chain head,
// the indexed range that is currently consistent with the chain and the valid
// range that has not been changed and has been consistent with all states of the
// chain since the previous SyncLogIndex or the creation of the matcher backend.
func (fm *FilterMapsMatcherBackend) SyncLogIndex(ctx context.Context) (SyncRange, error) {
	syncCh := make(chan SyncRange, 1)
	fm.f.matchersLock.Lock()
	fm.syncCh = syncCh
	fm.f.matchersLock.Unlock()

	select {
	case fm.f.matcherSyncCh <- fm:
	case <-ctx.Done():
		return SyncRange{}, ctx.Err()
	case <-fm.f.disabledCh:
		return SyncRange{IndexedView: fm.f.indexedView}, nil
	}
	select {
	case vr := <-syncCh:
		return vr, nil
	case <-ctx.Done():
		return SyncRange{}, ctx.Err()
	case <-fm.f.disabledCh:
		return SyncRange{IndexedView: fm.f.indexedView}, nil
	}
}

// updateMatchersValidRange iterates through active matchers and limits their
// valid range with the current indexed range. This function should be called
// whenever a part of the log index has been removed, before adding new blocks
// to it.
// Note that this function assumes that the index read lock is being held.
func (f *FilterMaps) updateMatchersValidRange() {
	f.matchersLock.Lock()
	defer f.matchersLock.Unlock()

	for fm := range f.matchers {
		if !f.indexedRange.initialized {
			fm.validBlocks = common.Range[uint64]{}
			continue
		}
		fm.validBlocks = fm.validBlocks.Intersection(f.indexedRange.blocks)
	}
}
